name: CI/CD Pipeline for Node.js + Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Install Node.js dependencies
    - name: Install Node.js dependencies
      run: npm install

    # Step 4: Run Node.js tests
    - name: Run Node.js tests
      run: npm test

    # Step 5: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 6: Install Python dependencies
    - name: Install Python dependencies
      run: pip install -r requirements.txt

    # Step 7: Run Python tests
    - name: Run Python tests
      run: pytest

    # Step 8: Build Docker image
    - name: Build Docker image
      run: docker build -t username/repository:tag .

    # Step 9: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 10: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push username/repository:tag

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Deploy Docker container to production
    - name: Deploy application
      run: |
        ssh user@server "docker pull username/repository:tag && docker-compose up -d"
