name: CI/CD Pipeline for Node.js + Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' 

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Node.js tests
        run: npm test

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Python tests
        run: pytest

      - name: Build Docker image
        run: docker build -t username/repository:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push username/repository:${{ github.sha }}

  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
      - name: Deploy application
        run: |
          ssh user@${{ secrets.SERVER_ADDRESS }} "docker pull username/repository:${{ github.sha }} && docker-compose up -d"